# https://coderabbit.ai/integrations/coderabbit-overrides.v2.json
language: "ja-JP"
early_access: false
reviews:
  high_level_summary: true
  poem: true
  review_status: true
  collapse_walkthrough: false
  path_filters: []
  path_instructions: []
  auto_review:
    enabled: true
    ignore_title_keywords:
      - "WIP"
      - "DO NOT MERGE"
    drafts: false
    base_branches: []
chat:
  auto_reply: true
