# https://github.com/jdx/mise#configuration
[tools]
python = {version='3.14.4'}
node = {version='24'}

"pipx:pre-commit" = "4.6.0"
"pipx:yamllint" = "1.38.0"

[settings]
experimental = true

[env]
TG_TF_PATH = "terraform"
