[env]
#_.python.venv = { path = ".venv", create = true }

[tools]
python = ['3.14.6']
go = ['1.26.4']
rust = ['1.96.0']
node = '24'
dotnet = '10.0.301'

uv = '0.11.23'
zellij = '0.44.3'
usage = '3.5.2'
#"github:podman-container-tools/podman" = { version = '5.8.3', matching = "podman-remote", rename_exe = "podman" }

"npm:prettier" = "3.8.4"
"npm:@commitlint/cli" = "21.1.0"
"npm:@devcontainers/cli" = "0.87.0"
"npm:conventional-changelog" = "7.2.1"
"npm:@openai/codex" = "0.142.2"
"npm:@github/copilot" = "1.0.65"

# pipx for cli (not library)
"pipx:pipenv" = "2026.6.2"
"pipx:poetry" = "2.4.1"
"pipx:pre-commit" = "4.6.0"
# "pipx:markitdown[all]" = "0.1.4"

[settings]
experimental = true
python.compile = true
idiomatic_version_file_enable_tools = []
