[env]
#_.python.venv = { path = ".venv", create = true }

[tools]
python = ['3.14.5']
go = ['1.26.3']
rust = ['1.95.0']
node = '24'
uv = '0.11.14'
zellij = '0.44.3'

"npm:prettier" = "3.8.3"
"npm:@commitlint/cli" = "21.0.1"
"npm:@devcontainers/cli" = "0.87.0"
"npm:conventional-changelog" = "7.2.0"
"npm:@openai/codex" = "0.131.0"
"npm:@github/copilot" = "1.0.48"

# pipx for cli (not library)
"pipx:pipenv" = "2026.6.1"
"pipx:poetry" = "2.4.1"
"pipx:pre-commit" = "4.6.0"
# "pipx:markitdown[all]" = "0.1.4"

[settings]
experimental = true
python.compile = true
idiomatic_version_file_enable_tools = []
