[env]
#_.python.venv = { path = ".venv", create = true }

[tools]
python = ['3.14.4']
go = ['1.26.2']
rust = ['1.94.1']
node = '24'
#"github:astral-sh/uv" = '0.9.18'
uv = '0.11.5'

"npm:renovate" = "43.110.7"
"npm:prettier" = "3.8.1"
"npm:@commitlint/cli" = "20.5.0"
"npm:@devcontainers/cli" = "0.85.0"
"npm:conventional-changelog" = "7.2.0"
"npm:release-please" = "17.4.1"
"npm:@openai/codex" = "0.120.0"
"npm:@github/copilot" = "1.0.24"

# pipx for cli (not library)
"pipx:pipenv" = "2026.5.2"
"pipx:poetry" = "2.3.3"
"pipx:pre-commit" = "4.5.1"
# "pipx:markitdown[all]" = "0.1.4"

[settings]
experimental = true
python.compile = true
idiomatic_version_file_enable_tools = []
