name: "Run install"
description: "Install dotfiles"

runs:
  using: "composite"
  steps:
    - name: Enable mise verbose logging
      if: runner.debug == '1'
      run: echo "MISE_VERBOSE=1" >> "$GITHUB_ENV"
      shell: bash

    - name: install
      run: ./install.sh
      shell: bash
      # explicitly set working directory
      working-directory: ${{ github.workspace }}

    - name: chezmoi data
      run: |
        $HOME/.local/bin/chezmoi data
        $HOME/.local/bin/chezmoi source-path
      shell: bash
