name: "Run install"
description: "Install dotfiles"

runs:
  using: "composite"
  steps:
    - name: install
      run: ./install.sh
      shell: bash
      # explicitly set working directory
      working-directory: ${{ github.workspace }}

    - name: chezmoi data
      run: '"$HOME/.local/bin/chezmoi" data'
      shell: bash
