name: "Mise hook env for actions"
description: "Mise hook env for actions"

runs:
  using: "composite"
  steps:
    - name: export
      run: ./export.sh
      shell: bash -l -eo pipefail {0}
      working-directory: ${{ github.action_path }}

    - name: check mise command
      run: |
        command -v mise || { echo "mise not found"; exit 1; }
      shell: bash -l -eo pipefail {0}
