name: CI Jobs

on:
  workflow_call:
    secrets:
      GH_APP_PEM_FILE:
        required: true

permissions: {}

jobs:
  super-linter:
    permissions:
      contents: read
      packages: read
      statuses: write
      # post results as pull requests comments
      issues: write
      pull-requests: write
    timeout-minutes: 10
    runs-on: ubuntu-latest
    if: github.event.action != 'closed'
    steps:
      - uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        id: gh-app-token
        with:
          client-id: ${{ vars.GH_APP_CLIENT_ID }}
          private-key: ${{ secrets.GH_APP_PEM_FILE }}
          permission-issues: write
          permission-pull-requests: write
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          # for super-linter
          fetch-depth: 0
          persist-credentials: false
      - name: load env
        run: |
          grep -v '#' .superlinterenv >> "$GITHUB_ENV"
      - uses: super-linter/super-linter/slim@9e863354e3ff62e0727d37183162c4a88873df41 # v8.6.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ENABLE_GITHUB_PULL_REQUEST_SUMMARY_COMMENT: false
          SAVE_SUPER_LINTER_SUMMARY: true
          ENABLE_GITHUB_ACTIONS_STEP_SUMMARY: false

      - name: Update sticky PR comment
        if: always() && github.event_name == 'pull_request'
        uses: marocchino/sticky-pull-request-comment@0ea0beb66eb9baf113663a64ec522f60e49231c0 # v3.0.4
        with:
          header: super-linter-report
          path: ${{ github.workspace }}/super-linter-output/super-linter-summary.md
          GITHUB_TOKEN: ${{ steps.gh-app-token.outputs.token }}

  run-install-vm:
    permissions:
      contents: read
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-24.04
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l -eo pipefail {0}
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
      - uses: ./.github/actions/run-install
      - name: mise env
        uses: ./.github/actions/mise-hook-env
      - name: lint
        run: |
          make lint
      - name: test
        run: |
          make test

  renovate:
    permissions:
      contents: read
      pull-requests: read
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
      - uses: suzuki-shunsuke/github-action-renovate-config-validator@ee9f69e1f683ed0d08225086482b34fc9abe9300 # v2.1.0
