name: Main Jobs

on:
  workflow_call:

permissions: {}

jobs:
  labeler:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    timeout-minutes: 10
    steps:
      # use GitHub Apps token to run other actions.
      - uses: actions/create-github-app-token@df432ceedc7162793a195dd1713ff69aefc7379e # v2.0.6
        id: gh-app-token
        with:
          app-id: ${{ secrets.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PEM_FILE }}
          permission-contents: read
          permission-pull-requests: write
      - uses: actions/labeler@8558fd74291d67161a8a78ce36a881fa63b766a9 # v5.0.0
        with:
          repo-token: ${{ steps.gh-app-token.outputs.token }}

  ci-jobs:
    uses: ./.github/workflows/_ci.yaml
    permissions:
      contents: read
      statuses: write
      pull-requests: read

  iac-jobs:
    needs: labeler
    if: contains(github.event.pull_request.labels.*.name, 'terraform-deps')
    uses: ./.github/workflows/_iac.yaml
    permissions:
      contents: read
      pull-requests: write
