name: check

on: # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  run-install-test:
    permissions: {}
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        distro: ["ubuntu-24.04", "debian-12"]
    container:
      image: mcr.microsoft.com/vscode/devcontainers/base:${{ matrix.distro }}
      env:
        CODESPACES: true
        REMOTE_CONTAINERS: true
    defaults:
      run:
        shell: bash -l -eo pipefail {0}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      # install for lint and test
      - uses: ./.github/actions/run-install
      - run: |
          git config --global --add safe.directory "${GITHUB_WORKSPACE}"
      - name: setup
        run: |
          make setup
      - name: mise env
        uses: ./.github/actions/mise-hook-env
      - name: lint
        run: |
          make lint
      - name: test
        run: |
          make test

  run-install-vm:
    permissions: {}
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-24.04
          - ubuntu-22.04
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - uses: ./.github/actions/run-install

  super-linter:
    permissions:
      statuses: write
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          # for super-linter
          fetch-depth: 0
          persist-credentials: false
      - name: load env
        run: |
          grep -v '#' .superlinterenv >> "$GITHUB_ENV"
      - uses: super-linter/super-linter/slim@12150456a73e248bdc94d0794898f94e23127c88 # v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  renovate:
    permissions:
      contents: read
      pull-requests: read
    timeout-minutes: 10
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l -eo pipefail {0}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - uses: ./.github/actions/run-install # for node.
      - name: setup
        run: |
          make setup
      - name: mise env
        uses: ./.github/actions/mise-hook-env
      - name: test renovate config
        run: |
          LOG_LEVEL=debug GH_TOKEN=${GH_TOKEN} make renovate
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  check-ci-result:
    needs: [run-install-test, run-install-vm, super-linter, renovate]
    runs-on: ubuntu-latest
    timeout-minutes: 5
    if: always()
    steps:
      - name: check results
        uses: air-hand/common-actions/assert-job-results@73b8f89422a45004462c715a10d2159667a57e06 # v1.2.4
        with:
          need-jobs: ${{ toJSON(needs) }}
