on:
  pull_request:
    branches:
      - main
    types:
      - labeled

permissions: {}

jobs:
  enable-auto-merge:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    if: contains(github.event.pull_request.labels.*.name, 'dependencies')
    permissions:
      pull-requests: write
    env:
      PR_URL: ${{ github.event.pull_request.html_url }}
    steps:
      - if: contains(github.event.pull_request.labels.*.name, 'patch') || contains(github.event.pull_request.labels.*.name, 'minor')
        name: enable auto merge patch version
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
