on:
  pull_request:
    branches:
      - main
    types:
      - labeled

permissions: {}

jobs:
  enable-auto-merge:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    if: contains(github.event.pull_request.labels.*.name, 'dependencies')
    env:
      PR_URL: ${{ github.event.pull_request.html_url }}
    steps:
      - uses: actions/create-github-app-token@67018539274d69449ef7c02e8e71183d1719ab42 # v2.1.4
        id: gh-app-token
        with:
          app-id: ${{ secrets.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PEM_FILE }}
          permission-contents: write
          permission-pull-requests: write
      - if: contains(github.event.pull_request.labels.*.name, 'patch') || contains(github.event.pull_request.labels.*.name, 'minor')
        name: enable auto merge minor and patch version
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          GH_TOKEN: ${{ steps.gh-app-token.outputs.token }}
