name: main

on: # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - closed

permissions: {}

jobs:
  main:
    uses: ./.github/workflows/_main.yaml
    permissions:
      contents: read
      pull-requests: write
      statuses: write
    secrets:
      GH_APP_ID: ${{ secrets.GH_APP_ID }}
      GH_APP_PEM_FILE: ${{ secrets.GH_APP_PEM_FILE }}
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
      TF_CLOUD_ORGANIZATION: ${{ secrets.TF_CLOUD_ORGANIZATION }}
      GH_APP_INSTALLATION_ID: ${{ secrets.GH_APP_INSTALLATION_ID }}

  check-result:
    needs: main
    runs-on: ubuntu-latest
    timeout-minutes: 5
    if: failure()
    steps:
      - name: exit with failure
        run: exit 1
