name: main

on: # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - closed

permissions: {}

jobs:
  call-main:
    uses: ./.github/workflows/_main.yaml
    permissions:
      contents: read
      pull-requests: write
      statuses: write
    secrets: inherit

  check-result:
    needs: call-main
    runs-on: ubuntu-latest
    timeout-minutes: 5
    if: failure()
    steps:
      - name: exit with failure
        run: exit 1

  check-ci-result:
    needs: call-main
    runs-on: ubuntu-latest
    timeout-minutes: 5
    if: failure()
    steps:
      - name: exit with failure
        run: exit 1

  check-tf-result:
    needs: call-main
    runs-on: ubuntu-latest
    timeout-minutes: 5
    if: failure()
    steps:
      - name: exit with failure
        run: exit 1
