name: "Rebase PRs auto merge enabled"

on:
  push:
    branches:
      - main

permissions: {}

jobs:
  rebase-auto-merge-enabled:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/create-github-app-token@21cfef2b496dd8ef5b904c159339626a10ad380e # v1.11.6
        id: gh-app-token
        with:
          app-id: ${{ secrets.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PEM_FILE }}
      - name: rebase
        uses: air-hand/common-actions/update-prs-auto-merge-enabled@ce745b3f8fea2e8aebe5808ba7a4d60f69ee6821 # v1.2.2
        with:
          token: ${{ steps.gh-app-token.outputs.token }}
          base_branch: main
