name: "Rebase PRs auto merge enabled"

on:
  push:
    branches:
      - main

permissions: {}

jobs:
  rebase-auto-merge-enabled:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/create-github-app-token@af35edadc00be37caa72ed9f3e6d5f7801bfdf09 # v1.11.7
        id: gh-app-token
        with:
          app-id: ${{ secrets.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PEM_FILE }}
      - name: rebase
        uses: air-hand/common-actions/update-prs-auto-merge-enabled@bca1843466dd4c82259742ac66ab122c746f7264 # v1.2.1
        with:
          token: ${{ steps.gh-app-token.outputs.token }}
          base_branch: main
